### ISSUE TITLE
Time to change the name bro 

### ISSUE THREAD

**Issue by krisk248** [jacobantony07/jacobantony07#1]
Lets change the name to jacobantony07 and then try changing other things too.

**Comment by jacobantony07** [comment]
wait what name? my username?

**Comment by jacobantony07** [comment]
wtf am i high lol??? i only saw till name and nothing after that lol. you want me to change the repo name or the file itself?

**Comment by jacobantony07** [comment]
#### wait why am i changing the name? :rofl:   just made this because i tht you were inactive in linkedin

**Comment by krisk248** [comment]
No lets start with simple things. No now change the repo name in the setting to jacobantony07 and let the jacob.md file be Readme.md . Then lets put various function inside Readme to  #look cool. Wat do you say???? 🤣🤣🤣🤣🤣🤣
